title: "Pranav Rao Balguri"
description: "Data Analytics Engineer | Snowflake · Power BI · Azure · SQL"
theme: minima

minima:
  skin: dark

author:
  name: "Pranav Rao Balguri"

header_pages:
  - index.md
